apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentop-tool.fullname" . }}-configmap
data:
  API_KEY: {{ uuidv4 }}
  {{- (.Files.Glob .Values.server.path).AsConfig | nindent 2 }}
  {{- .Values.server.script | toYaml | nindent 2 }}
