{{- if .Values.ttl.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentop-tool.fullname" . }}-ttl-serviceaccount
  labels:
    {{- include "agentop-tool.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
