{{- if .Values.serviceAccount.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "agentop-management.fullname" . }}-clusterrolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "agentop-management.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:                                                                                                                  
  kind: ClusterRole
  name: {{ include "agentop-management.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end }}   
